### ISSUE TITLE
Incompatible with Java 9

### ISSUE THREAD

**Issue by liujed** [polyglot-compiler/polyglot#6]
Polyglot is currently incompatible with Java 9:
```
$ echo 'class test {}' > test.jl
$ jlc test.jl
/tmp/test.jl:1: Cannot find class "java.lang.Object"; Class 
    "java.lang.Object" not found.
class test {}
^-----------^

1 error.
```
This appears to be caused by [JEP 220](http://openjdk.java.net/jeps/220#Removed:-rt-jar-and-tools-jar), which removed tools.jar, which Polyglot's class resolver uses to look up system classes, such as `java.lang.Object`. I suspect a fix to this issue might involve using the Java Reflection API instead of relying on having these system classes on the classpath.

**Comment by liujed** [comment]
For reference, here is the call chain that occurs when Polyglot searches for a new class (outermost calls to innermost):
```
TypeSystem_c.forName(Resolver, String) line 1761
SystemResolver.find(String) line 214
CachingResolver.find(String) line 142
SourceClassResolver.find(String) line 159
LoadedClassResolver.loadFile(String) line 90
ExtFileManager.loadFile(String) line 383
ExtFileManager.loadFile(JavaFileManager.Location, String) line 403
ExtFileManager.getJavaFileForInput(JavaFileManager.Location, String, JavaFileObject.Kind) line 160
ExtFileManager.getFileForInput(JavaFileManager.Location, String, String) line 151
ForwardingJavaFileManager.getFileForInput(JavaFileManager.Location, String, String) line 144
JavacFileManager.getFileForInput(JavaFileManager.Location, String, String) line 783
JavacFileManager.getFileForInput(JavaFileManager.Location, RelativePath.RelativeFile) line 787
```
The method `ExtFileManager.loadFile(String)` first searches the user-provided classpath (`StandardLocation.CLASS_PATH`) before falling back on `StandardLocation.PLATFORM_CLASS_PATH`. The method `JavacFileManager.getFileForInput()` converts these `StandardLocation` objects into a file system path that gets searched. In Java 8 and below, the `PLATFORM_CLASS_PATH` corresponds to a path that includes `rt.jar`, but in Java 9, it corresponds to the empty path.

One approach to fixing this issue might be to fall back on reflection (perhaps going through the platform class loader or the bootstrap class loader) for the raw class if `LoadedClassResolver.loadFile(String)` comes up empty in `SourceClassResolver.find(String)`.

**Comment by andrewcmyers** [comment]
Closed for now.
